{
  "modified": "2023-08-28T14:03:06Z",
  "published": "2023-08-22T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "PSF-0000-a8fc8da554f518ff",
  "aliases": [
    "CVE-2022-48560"
  ],
  "summary": "Use-after-free in heappushpop() of heapq module",
  "details": "A use-after-free exists in Python through 3.9 via heappushpop in heapq.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "79f89e6e5a659846d1068e8b1bd8e491ccdef861"
            },
            {
              "fixed": "958064f8d2b84062b0582bbae911df8ccfc11fd6"
            },
            {
              "fixed": "993811ffe75c2573f97fb3fd1414b34609b8c8db"
            },
            {
              "fixed": "c563f409ea30bcb0623d785428c9257917371b76"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://www.cve.org/CVERecord?id=CVE-2022-48560"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue39421"
    },
    {
      "type": "PATCH",
      "url": "https://github.com/python/cpython/pull/18118"
    }
  ],
  "database_specific": {
    "cwe_ids": []
  }
}