{
  "modified": "2024-09-04T22:31:34.780Z",
  "published": "2024-08-22T18:45:31.807Z",
  "schema_version": "1.5.0",
  "id": "PSF-2024-10",
  "aliases": [
    "CVE-2024-8088"
  ],
  "details": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule affecting \"zipfile.Path\". Note that the more common API \"zipfile.ZipFile\" class is unaffected.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.Path\" like \"namelist()\", \"iterdir()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "795f2597a4be988e2bb19b69ff9958e981cb894e"
            },
            {
              "fixed": "8c7348939d8a3ecd79d630075f6be1b0c5b41f64"
            },
            {
              "fixed": "dcc5182f27c1500006a1ef78e10613bb45788dea"
            },
            {
              "fixed": "e0264a61119d551658d9445af38323ba94fc16db"
            },
            {
              "fixed": "2231286d78d328c2f575e0b05b16fe447d1656d6"
            },
            {
              "fixed": "7e8883a3f04d308302361aeffc73e0e9837f19d4"
            },
            {
              "fixed": "95b073bddefa6243effa08e131e297c0383e7f6a"
            },
            {
              "fixed": "7bc367e464ce50b956dd232c1dfa1cad4e7fb814"
            },
            {
              "fixed": "962055268ed4f2ca1d717bfc8b6385de50a23ab7"
            },
            {
              "fixed": "fc0b8259e693caa8400fa8b6ac1e494e47ea7798"
            },
            {
              "fixed": "0aa1ee22ab6e204e9d3d0e9dd63ea648ed691ef1"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/pull/122906"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/python/cpython/issues/122905"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/python/cpython/issues/123270"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/2231286d78d328c2f575e0b05b16fe447d1656d6"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/7e8883a3f04d308302361aeffc73e0e9837f19d4"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/95b073bddefa6243effa08e131e297c0383e7f6a"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/7bc367e464ce50b956dd232c1dfa1cad4e7fb814"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/962055268ed4f2ca1d717bfc8b6385de50a23ab7"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/fc0b8259e693caa8400fa8b6ac1e494e47ea7798"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/0aa1ee22ab6e204e9d3d0e9dd63ea648ed691ef1"
    }
  ],
  "database_specific": {
    "cwe_ids": []
  }
}