{
  "modified": "2023-08-25T16:05:33Z",
  "published": "2022-03-04T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "PSF-2022-7",
  "aliases": [
    "CVE-2021-3737"
  ],
  "summary": "CVE-2021-3737: urllib HTTP client possible infinite loop on a 100 Continue response",
  "details": "A flaw was found in python. An improperly handled HTTP response in the HTTP client code of python may allow a remote attacker, who controls the HTTP server, to make the client script enter an infinite loop, consuming CPU time. The highest threat from this vulnerability is to system availability.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "078b146f062d212919d0ba25e34e658a8234aa63"
            },
            {
              "fixed": "47895e31b6f626bc6ce47d175fe9d43c1098909d"
            },
            {
              "fixed": "60ba0b68470a584103e28958d91e93a6db37ec92"
            },
            {
              "fixed": "ea9327036680acc92d9f89eaf6f6a54d2f8d78d9"
            },
            {
              "fixed": "f396864ddfe914531b5856d7bf852808ebfc01ae"
            },
            {
              "fixed": "f68d2d69f1da56c2aea1293ecf93ab69a6010ad7"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "database_specific": {
    "cwe_ids": []
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://access.redhat.com/security/cve/CVE-2021-3737"
    },
    {
      "type": "ADVISORY",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1995162"
    },
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue44022"
    }
  ]
}