{
  "modified": "2021-08-29T06:06:43Z",
  "published": "2016-06-30T17:00:00Z",
  "schema_version": "1.5.0",
  "id": "PSF-2016-5",
  "aliases": [
    "CVE-2016-3189"
  ],
  "summary": "Windows: vulnerable bzip2 1.0.6",
  "details": "Use-after-free vulnerability in bzip2recover in bzip2 1.0.6 allows remote attackers to cause a denial of service (crash) via a crafted bzip2 file, related to block ends set to before the start of the block.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4a3c610cd635f14747cf02c77908e80620aae6ea"
            },
            {
              "fixed": "58d576a43cb1800dd68f06a429d7d41f746a8c01"
            },
            {
              "fixed": "6649519e67841b1aa12672f1d9b5cb24494f6196"
            },
            {
              "fixed": "e1639f361ee0dfbf08bb8538839d3d557c1a995c"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "database_specific": {
    "cwe_ids": []
  },
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue44549"
    }
  ]
}