{
  "modified": "2023-08-28T16:57:11Z",
  "published": "2023-08-24T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "PSF-2023-5",
  "aliases": [
    "CVE-2022-48566",
    "GHSA-crhm-wc96-7579"
  ],
  "summary": "XML External Entity issue in plistlib module",
  "details": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "05ee790f4d1cd8725a90b54268fc1dfe5b4d1fa2"
            },
            {
              "fixed": "479553c7c11306a09ce34edb6ef208133b7b95fe"
            },
            {
              "fixed": "65894cac0835cb8f469f649e20aa1be8bf89f5ae"
            },
            {
              "fixed": "e512bc799e3864fe3b1351757261762d63471efc"
            },
            {
              "fixed": "a158fb9c5138db94adf24fbc5690467cda811163"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-48565"
    },
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue42051"
    }
  ]
}
