{
  "modified": "2023-08-24T00:00:00Z",
  "published": "2023-08-24T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "PSF-0000-CVE-2022-48565",
  "aliases": [
    "CVE-2022-48566",
    "GHSA-cgfh-jp5w-8cmx"
  ],
  "summary": "Reference count issue in _asyncio._swap_current_task()",
  "details": "An issue in Python CPython 3.12.0b1 allows an attacker to obtain sensitive information via the _asyncio._swap_current_task() component.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "a474e04388c2ef6aca75c26cb70a1b6200235feb"
            },
            {
              "fixed": "d2cbb6e918d9ea39f0dd44acb53270f2dac07454"
            },
            {
              "fixed": "9e6f8d46150c1a0af09d68ce63c603cf321994aa"
            }
          ],
          "repo": "https://github.com/python/cpython"
        },
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "3.12.0b1"
            },
            {
              "fixed": "3.12.0rc2"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-38898"
    },
    {
      "type": "WEB",
      "url": "https://github.com/python/cpython/issues/105987"
    }
  ]
}
