{
  "modified": "2023-05-24T00:00:00Z",
  "published": "2020-01-30T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "PSF-2020-8",
  "aliases": [
    "CVE-2020-8492"
  ],
  "summary": "urllib basic auth regex denial of service",
  "details": "Python 2.7 through 2.7.17, 3.5 through 3.5.9, 3.6 through 3.6.10, 3.7 through 3.7.6, and 3.8 through 3.8.1 allows an HTTP server to conduct Regular Expression Denial of Service (ReDoS) attacks against a client because of urllib.request.AbstractBasicAuthHandler catastrophic backtracking.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0b297d4ff1c0e4480ad33acae793fbaf4bf015b4"
            },
            {
              "fixed": "37fe316479e0b6906a74b0c0a5e495c55037fdfd"
            },
            {
              "fixed": "69cdeeb93e0830004a495ed854022425b93b3f3e"
            },
            {
              "fixed": "b57a73694e26e8b2391731b5ee0b1be59437388e"
            },
            {
              "fixed": "ea9e240aa02372440be8024acb110371f69c9d41"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "database_specific": {
    "cwe_ids": []
  },
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue38826"
    },
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue39503"
    }
  ]
}