{
  "modified": "2013-01-29T10:00:00Z",
  "published": "2012-08-14T22:00:00Z",
  "schema_version": "1.5.0",
  "id": "PSF-2012-6",
  "aliases": [
    "CVE-2012-2135"
  ],
  "summary": "Vulnerability in the utf-16 decoder after error handling",
  "details": "The utf-16 decoder in Python 3.1 through 3.3 does not update the aligned_end variable after calling the unicode_decode_call_errorhandler function, which allows remote attackers to obtain sensitive information (process memory) or cause a denial of service (memory corruption and crash) via unspecified vectors.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "715a63b78349952ccc0fb3dd3139e2d822006d35"
            },
            {
              "fixed": "b4bbee25b1e3f4bccac222f806b3138fb72439d6"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "database_specific": {
    "cwe_ids": []
  }
}
